### ISSUE TITLE
获取财报揭露的方法

### ISSUE THREAD

**Issue by hellobiek** [datochan/DTGear#11]
发现从http://www.cninfo.com.cn/new/commonUrl?url=data/yypl这里获取比较容易。
从同花顺获取，太容易失败了。

**Comment by datochan** [comment]
嗯，嗯，多谢~~~

**Comment by datochan** [comment]
我临时用了一下，发现历史数据比较少，而同花顺的数据错误率比较高。
我考虑了一下，其实数据披露的及时性并不是非常重要，只要在分析时采用同样的分析方法对后续的操作都是能起到作用的。
我参考这个页面: [理杏仁指数的财务数据计算说明文档](https://www.lixinger.com/wiki/stock-collection-fs-calculation), 打算将程序也修改为这种计算方式，不再考虑财报披露时间的问题。
