### ISSUE TITLE
更新成分股的脚本能补上吗？这个还蛮有用的

### ISSUE THREAD

**Issue by royburns** [datochan/DTGear#3]
这个还蛮有用的

**Comment by datochan** [comment]
嗯，您感兴趣的点跟我一致。

跟您分享一下我的最新进展:
1. 历史成分股，我是爬取金融届的网站，但是由于一些退市，停牌等因素导致历史成分不全。我也找过通联数据，购买相关数据，但是那价格，我一个月薪几千元的小散户真心不敢想。
2. 最新成分股，这个每年两次，根据中证指数的网站，手工更新的，纯体力活，我就不公开了~

**Comment by datochan** [comment]
如果你有别的我的方式，也希望能共享出来，我也很需要，哈哈~

**Comment by royburns** [comment]
了解
tushare.pro那听过吗，创始人是米哥，通联出来的，他做的一个数据平台，里面有成分股的数据
https://tushare.pro/document/2?doc_id=96
你看看能否接入刀DTGear里面来，

需要注册，如果你没有注册的话，可以用我的邀请链接，双方都有积分，有些数据需要积分，但是基本上大多数数据都能用
https://tushare.pro/register?reg=124655

**Comment by datochan** [comment]
> 了解
> tushare.pro那听过吗，创始人是米哥，通联出来的，他做的一个数据平台，里面有成分股的数据
> https://tushare.pro/document/2?doc_id=96
> 你看看能否接入刀DTGear里面来，
> 
> 需要注册，如果你没有注册的话，可以用我的邀请链接，双方都有积分，有些数据需要积分，但是基本上大多数数据都能用
> https://tushare.pro/register?reg=124655

嗯，这个我最初用过他的: http://tushare.org/ 这个，但是它好多数据的质量不是很好。他更新到pro版本之后，我也试着用过，他的指数成分并不完整，而且接口的调用还有限制，就抛弃不用了。

**Comment by royburns** [comment]
哈哈哈，好吧，要是再找到更好的就再过来留言

**Comment by datochan** [comment]
我现在对于成分股的要求降低了好多，目前的要求是，大致能跟踪到指数就行，不要求那么严格的正确性。

毕竟ETF跟踪起指数来也是有偏差的，没必要那么较真儿。

当然，这个程序主要也是我个人使用，所以也就不讲究了....
哈哈~

**Comment by royburns** [comment]
嗯明白
这个程序做的很棒啊，该有的都有了
比较适合价值+趋势的人使用

**Comment by datochan** [comment]
我本来是想根据这些做个股的量化组合轮动的。发现工作量太大，业务时间无法支持我做这种工作。

就改做基金定投了，基金定投的话需要对大盘有个定位，就参考雪球还有一些大v做的那些估值表写了这个小程序。

目前来看，自己用着还算不错的，哈哈~

**Comment by abc100m** [comment]
大佬炒基金赚到钱了不？ 如有好的策略求分享 :-)

**Comment by datochan** [comment]
我发现在优矿中可以使用之前的通联数据接口，我将获取成分股的脚本更新在ReadMe.md中了。
