### ISSUE TITLE
获取全量财报披露时间的时候有可能被干掉。

### ISSUE THREAD

**Issue by hellobiek** [datochan/DTGear#4]
有一个请求时间特别长，且获取的结果为空，貌似被发现后，被处理掉了。。
![image](https://user-images.githubusercontent.com/2854520/58872838-789b5280-86f7-11e9-9a25-f5f7bed01f68.png)

 <div class="page-loading" style="display: none;">
        <div class="mask"></div>
        <div class="loading-img"></div>
    </div>
    <table class="m-table J-ajax-table J-canvas-table">
        <thead>
                <tr class ="row2">
            <th width="40">序号</th>
            <th width="172"  colidx="1"><a href="###" class="J-ajax-a" field="stockcode" >股票代码</a><i class="arr-down"></i></th>
            <th width="172">股票简称</th>
            <th width="203" ><a href="###" class="J-ajax-a" field="sc" >首次预约时间</a><i class="arr-down"></i></th>
            <th width="203" >变更时间</th>
            <th width="203" ><a href="###" class="J-ajax-a" field="sj" >实际披露时间</a><i class="arr-down"></i></th>
            <th width="129">历史业绩数据</th>
        </tr>
                </thead>
        <tbody>
                </tbody>
    </table>
    <div class="m-page J-ajax-page">
    	 
    </div>

**Comment by hellobiek** [comment]
爬虫有风险啊，哈哈，即使能算出cookie。

**Comment by datochan** [comment]
是的，只要公开的，一般都很难继续长久使用了。
程序中，通达信的财报也是这样，原先的方式不让用了，处理掉了~

**Comment by hellobiek** [comment]
不是你的代码被封了，是有反爬虫系统，非常细致。

数据爬虫爬取的和你人眼看到的，数据项目都不一样。

**Comment by hellobiek** [comment]
![image](https://user-images.githubusercontent.com/2854520/59025407-ac58b280-8886-11e9-8059-9905b204ecc1.png)

最近抽风了，研究了下爬虫，感觉反爬虫真是坑爹。

**Comment by hellobiek** [comment]
昨天测试了下，用了下免费的代理，完美的解决了反爬虫。

代理的github地址：https://github.com/jhao104/proxy_pool

哈哈，暂时领先反爬虫，等待反爬虫反击。。。。。。。
