### ISSUE TITLE
部分财报的数据有一点问题，告知如下。

### ISSUE THREAD

**Issue by hellobiek** [datochan/DTGear#6]
1. 600503在20031231号的年报，一直到20041221才发布，但是他的三季报20040930却在20040930就发布了。
2. 000755的数据预报20170808，但是实际却20160808就发布了。
![image](https://user-images.githubusercontent.com/2854520/60767957-a1957580-a0f1-11e9-8b1a-6658b4b5a776.png)

**Comment by datochan** [comment]
打算在后续的版本中抛弃财报披露时间这个因素，具体参考 #11
