### ISSUE TITLE
计算指数或行业的估值的方法。

### ISSUE THREAD

**Issue by hellobiek** [datochan/DTGear#7]
我觉得中证指数提供的这总方法更为合适。计算说明如下（其他指标的计算也在相同网址内）：

http://www.csindex.com.cn/uploads/downloads/pe_ratio/files/gxl.pdf
http://www.csindex.com.cn/uploads/downloads/pe_ratio/files/jtsyl.pdf

仅供参考！

**Comment by datochan** [comment]
多谢，
您的意思是，找到指数的成分股然后采用这种方法计算股息率和市盈率吗？

我认为这个计算方法确实比我现在主观的计算方法更合适。
因为pdf的上级网址无法访问，能否给出相应的网页，我也看看其它的指标。

**Comment by hellobiek** [comment]
PB:http://www.csindex.com.cn/uploads/downloads/pe_ratio/files/sjl.pdf
TTM:http://www.csindex.com.cn/uploads/downloads/pe_ratio/files/gdsyl.pdf

**Comment by hellobiek** [comment]
最终的结果应该是有一个类似的图
![PE-BAND](https://user-images.githubusercontent.com/2854520/61589900-4da38a00-abe3-11e9-82b6-ef19c29ca0ba.jpg)

**Comment by datochan** [comment]
最近有时间，我又网上找了一下关于指数、行业之类估值的计算方法。
想看看如何再按照您提的方式再优化一下。现在感觉这个PE，PB的计算方式比我想的要复杂的多。

现在我程序是主观采用中位数的估值作为指数估值的。如果采用其它方式也跟中位数是一样的，都存在各种缺陷。
目前我找到描述比较完善的一篇文章是这个: https://www.lixinger.com/wiki/stock-collection-value-calculation/

我自己评估下来，感觉还是继续使用中位数的估值作为指数估值。
