### ISSUE TITLE
获取成分股的方法

### ISSUE THREAD

**Issue by hellobiek** [datochan/DTGear#9]
https://www.joinquant.com/help/api/help?name=JQData#get_industry-%E6%9F%A5%E8%AF%A2%E8%82%A1%E7%A5%A8%E6%89%80%E5%B1%9E%E8%A1%8C%E4%B8%9A

我发现使用juquant的方式是比较合适的方法，可以放到本地存储。数据基本上可以追溯到2005年。

**Comment by datochan** [comment]
我发现在优矿中可以直接免费的使用之前通联数据的接口，所以我改写了一下。过去成员股的代码放在ReadMe.md中。
